// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");

((require('isomorphic-fetch')));

function buildQueryString(param) {
  return param[/* key */0] + ("=" + param[/* value */1]);
}

function request(endpoint, config) {
  var match = config[/* queryString */1];
  var urlWithQueryString;
  if (match !== undefined) {
    var match$1 = match;
    urlWithQueryString = match$1 ? endpoint + ("?" + (buildQueryString(match$1[0]) + List.fold_left((function (a, b) {
                  return a + ("&" + buildQueryString(b));
                }), "&", match$1[1]))) : endpoint;
  } else {
    urlWithQueryString = endpoint;
  }
  return fetch(urlWithQueryString).then((function (prim) {
                    return prim.text();
                  })).then((function (text) {
                  return Promise.resolve(text);
                })).catch((function (error) {
                console.log(error);
                return Promise.resolve(undefined);
              }));
}

exports.buildQueryString = buildQueryString;
exports.request = request;
/*  Not a pure module */
