// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Fetch = require("bs-fetch/src/Fetch.js");
var Types = require("./Types.bs.js");
var Future = require("reason-future/src/Future.bs.js");
var FutureJs = require("reason-future/src/FutureJs.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

((require('isomorphic-fetch')));

var idpEndpoint = "https://cognito-idp.us-east-2.amazonaws.com/";

function makeNetworkError(err) {
  return /* NetworkError */[err];
}

function request(operation, params) {
  var headers = { };
  params["ClientId"] = "3vjshpa4lgf92nfisjrg9os21a";
  params["AuthFlow"] = "USER_PASSWORD_AUTH";
  headers["Content-Type"] = "application/x-amz-json-1.1";
  headers["X-Amz-User-Agent"] = "aws-amplify/0.1.x js";
  headers["X-Amz-Target"] = "AWSCognitoIdentityProviderService." + Types.operationToJs(operation);
  return Future.flatMapOk(Future.mapOk(FutureJs.fromPromise(fetch(idpEndpoint, Fetch.RequestInit[/* make */0](/* Post */2, Caml_option.some(headers), Caml_option.some(JSON.stringify(params)), undefined, undefined, /* NoCORS */2, undefined, /* NoCache */3, undefined, undefined, undefined)(/* () */0)), makeNetworkError), (function (prim) {
                    return prim.json();
                  })), (function (json) {
                return FutureJs.fromPromise(json, makeNetworkError);
              }));
}

function buildQueryString(param) {
  return param[/* key */0] + ("=" + param[/* value */1]);
}

function make(values) {
  if (values) {
    return "?" + (buildQueryString(values[0]) + List.fold_left((function (a, b) {
                    return a + ("&" + buildQueryString(b));
                  }), "&", values[1]));
  } else {
    return "";
  }
}

var QueryString = /* module */[
  /* buildQueryString */buildQueryString,
  /* make */make
];

exports.idpEndpoint = idpEndpoint;
exports.makeNetworkError = makeNetworkError;
exports.request = request;
exports.QueryString = QueryString;
/*  Not a pure module */
