// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Caml_js_exceptions = require("bs-platform/lib/js/caml_js_exceptions.js");

function subfunction(param) {
  try {
    return Js_exn.raiseError("oops");
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      var match = exn[1].message;
      if (match !== undefined) {
        console.log("Error: " + (String(match) + ""));
        return /* () */0;
      } else {
        console.log("An unknown error occurred");
        return /* () */0;
      }
    } else {
      throw exn;
    }
  }
}

exports.subfunction = subfunction;
/* No side effect */
