// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var CognitoJson_bs = require("./atd/CognitoJson_bs.bs.js");

function make(param) {
  var message = param[/* message */1];
  switch (param[/* __type */0]) {
    case "InternalErrorException" :
        return /* `CognitoInternalError */[
                636052602,
                message
              ];
    case "InvalidLambdaResponseException" :
        return /* `CognitoInvalidLambdaResponse */[
                -1072578002,
                message
              ];
    case "InvalidParameterException" :
        return /* `CognitoInvalidParameter */[
                -267133469,
                message
              ];
    case "NotAuthorizedException" :
        return /* `CognitoNotAuthorized */[
                -1019683139,
                message
              ];
    case "ResourceNotFoundException" :
        return /* `CognitoResourceNotFound */[
                281060686,
                message
              ];
    case "TooManyRequestsException" :
        return /* `CognitoTooManyRequests */[
                165203366,
                message
              ];
    case "UnexpectedLambdaException" :
        return /* `CognitoUnexpectedLambda */[
                -539579927,
                message
              ];
    case "UserLambdaValidationException" :
        return /* `CognitoUserLambdaValidation */[
                1019055420,
                message
              ];
    default:
      return ;
  }
}

function makeFromJson(json) {
  return make(Curry._1(CognitoJson_bs.read_error, json));
}

var Common = {
  make: make,
  makeFromJson: makeFromJson
};

function make$1(param) {
  var message = param[/* message */1];
  switch (param[/* __type */0]) {
    case "CodeDeliveryFailureException" :
        return /* `CognitoCodeDeliveryFailure */[
                307717752,
                message
              ];
    case "InvalidEmailRoleAccessPolicyException" :
        return /* `CognitoInvalidEmailRoleAccessPolicy */[
                -320011326,
                message
              ];
    case "InvalidPasswordException" :
        return /* `CognitoInvalidPassword */[
                -17702879,
                message
              ];
    case "InvalidSmsRoleAccessPolicysException" :
        return /* `CognitoInvalidSmsRoleAccessPolicys */[
                598714580,
                message
              ];
    case "InvalidSmsRoleTrustRelationshipException" :
        return /* `CognitoInvalidSmsRoleTrustRelationship */[
                -198400121,
                message
              ];
    case "UsernameExistsException" :
        return /* `CognitoUsernameExists */[
                -157849469,
                message
              ];
    default:
      return /* ReasonCognitoUnknownError */536808491;
  }
}

function makeFromJson$1(json) {
  var err = Curry._1(CognitoJson_bs.read_error, json);
  var match = make(err);
  if (match !== undefined) {
    return match;
  } else {
    return make$1(err);
  }
}

var ConfirmSignUp = {
  make: make$1,
  makeFromJson: makeFromJson$1
};

function make$2(param) {
  var message = param[/* message */1];
  switch (param[/* __type */0]) {
    case "CodeDeliveryFailureException" :
        return /* `CognitoCodeDeliveryFailure */[
                307717752,
                message
              ];
    case "InvalidEmailRoleAccessPolicyException" :
        return /* `CognitoInvalidEmailRoleAccessPolicy */[
                -320011326,
                message
              ];
    case "InvalidPasswordException" :
        return /* `CognitoInvalidPassword */[
                -17702879,
                message
              ];
    case "InvalidSmsRoleAccessPolicysException" :
        return /* `CognitoInvalidSmsRoleAccessPolicys */[
                598714580,
                message
              ];
    case "InvalidSmsRoleTrustRelationshipException" :
        return /* `CognitoInvalidSmsRoleTrustRelationship */[
                -198400121,
                message
              ];
    case "UsernameExistsException" :
        return /* `CognitoUsernameExists */[
                -157849469,
                message
              ];
    default:
      return /* ReasonCognitoUnknownError */536808491;
  }
}

function makeFromJson$2(json) {
  var err = Curry._1(CognitoJson_bs.read_error, json);
  var match = make(err);
  if (match !== undefined) {
    return match;
  } else {
    return make$2(err);
  }
}

var SignUpErrors = {
  make: make$2,
  makeFromJson: makeFromJson$2
};

function make$3(param) {
  var message = param[/* message */1];
  switch (param[/* __type */0]) {
    case "InvalidSmsRoleAccessPolicysException" :
        return /* `CognitoInvalidSmsRoleAccessPolicys */[
                598714580,
                message
              ];
    case "InvalidSmsRoleTrustRelationshipException" :
        return /* `CognitoInvalidSmsRoleTrustRelationship */[
                -198400121,
                message
              ];
    case "InvalidUserPoolConfigurationException" :
        return /* `CognitoInvalidUserPoolConfiguration */[
                992401065,
                message
              ];
    case "PasswordResetRequiredException" :
        return /* `CognitoPasswordResetRequired */[
                959433314,
                message
              ];
    case "UserNotConfirmedException" :
        return /* `CognitoUserNotConfirmed */[
                937418472,
                message
              ];
    case "UserNotFoundException" :
        return /* `CognitoUserNotFound */[
                376697675,
                message
              ];
    default:
      return /* ReasonCognitoUnknownError */536808491;
  }
}

function makeFromJson$3(json) {
  var err = Curry._1(CognitoJson_bs.read_error, json);
  var match = make(err);
  if (match !== undefined) {
    return match;
  } else {
    return make$3(err);
  }
}

var InitiateAuth = {
  make: make$3,
  makeFromJson: makeFromJson$3
};

exports.Common = Common;
exports.ConfirmSignUp = ConfirmSignUp;
exports.SignUpErrors = SignUpErrors;
exports.InitiateAuth = InitiateAuth;
/* CognitoJson_bs Not a pure module */
