// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_json = require("bs-platform/lib/js/js_json.js");

var username = {
  USERNAME: "Bob"
};

var params = {
  AuthFlow: "CUSTOM_AUTH",
  AuthParameters: username
};

console.log("params", Js_json.test(params, /* Object */2));

function coordinatesToJs(param) {
  return {
          x: param[/* x */0],
          y: param[/* y */1]
        };
}

function coordinatesFromJs(param) {
  return /* record */[
          /* x */param.x,
          /* y */param.y
        ];
}

var jsCoordinates = {
  x: /* x */1,
  y: /* y */2
};

console.log("jsCoordinates", Js_json.test(jsCoordinates, /* Object */2));

var auth_bsd = {
  USERNAME: "Test",
  PASSWORD: "Test"
};

console.log("auth_bsd", auth_bsd);

var params_bsd = {
  AuthFlow: "USER_PASSWORD_AUTH",
  AuthParameters: auth_bsd
};

console.log("params_bsd", params_bsd);

exports.params = params;
exports.coordinatesToJs = coordinatesToJs;
exports.coordinatesFromJs = coordinatesFromJs;
exports.jsCoordinates = jsCoordinates;
exports.auth_bsd = auth_bsd;
exports.params_bsd = params_bsd;
/*  Not a pure module */
