// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cognito = require("./Cognito.bs.js");

var auth = Cognito.makeConfig("1234", "1234", /* UsEast1 */0, undefined, /* () */0);

var testRequest = Cognito.signUp(auth, "sometestuser", "Password12345@", undefined, undefined, /* () */0);

exports.auth = auth;
exports.testRequest = testRequest;
/* auth Not a pure module */
