// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var SRP = require("./srp/SRP.bs.js");
var Future = require("reason-future/src/Future.bs.js");
var Cognito = require("./Cognito.bs.js");

SRP.make(SRP.KnownSafePrimes.bit3072);

var auth = Cognito.Config.make("us-east-2_pTFKTGtS3", "3vjshpa4lgf92nfisjrg9os21a", /* UsEast2 */1, undefined, /* () */0);

var authParameters = { };

authParameters["USERNAME"] = "sarah7";

authParameters["PASSWORD"] = "Password12345@!";

Future.tapError(Cognito.initiateSRPAuth(auth, authParameters, undefined, undefined, undefined, /* () */0), (function (result) {
        console.log("err!", result);
        return /* () */0;
      }));

exports.auth = auth;
exports.authParameters = authParameters;
/*  Not a pure module */
