// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Future = require("reason-future/src/Future.bs.js");
var Cognito = require("./Cognito.bs.js");

var auth = Cognito.makeConfig("us-east-2_pTFKTGtS3", "3vjshpa4lgf92nfisjrg9os21a", /* UsEast2 */1, undefined, /* () */0);

var emailAttribute = { };

emailAttribute["Name"] = "email";

emailAttribute["Value"] = "reasoncog@pck.email";

var testRequest = Future.tapError(Future.tapOk(Cognito.signUp(auth, "sarah6", "Password12345@", /* array */[emailAttribute], undefined, /* () */0), (function (value) {
            console.log("OK", value);
            return /* () */0;
          })), (function (value) {
        console.log("err", value);
        return /* () */0;
      }));

exports.auth = auth;
exports.emailAttribute = emailAttribute;
exports.testRequest = testRequest;
/* auth Not a pure module */
