// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cognito = require("./Cognito.bs.js");

var auth = Cognito.makeConfig("us-east-2_pTFKTGtS3", "3vjshpa4lgf92nfisjrg9os21a", /* UsEast2 */1, undefined, /* () */0);

var emailAttribute = { };

emailAttribute["Name"] = "email";

emailAttribute["Value"] = "aa.rmand.inbox@gmail.com";

var signIn = Cognito.signIn(auth, "sometestuser2", "Password12345#", /* () */0);

exports.auth = auth;
exports.emailAttribute = emailAttribute;
exports.signIn = signIn;
/* auth Not a pure module */
