// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


function makeOperationString(param) {
  switch (param) {
    case 0 : 
        return "SignUp";
    case 1 : 
        return "SignIn";
    case 2 : 
        return "ConfirmSignUp";
    case 3 : 
        return "ChangePassword";
    case 4 : 
        return "RespondToAuthChallenge";
    case 5 : 
        return "ForgotPassword";
    case 6 : 
        return "ConfirmForgotPassword";
    case 7 : 
        return "InitiateAuth";
    
  }
}

function makeRegionString(param) {
  switch (param) {
    case 0 : 
        return "us-east-1";
    case 1 : 
        return "us-east-2";
    case 2 : 
        return "us-west-2";
    case 3 : 
        return "ap-south-1";
    case 4 : 
    case 5 : 
        return "ap-northeast-2";
    case 6 : 
        return "ap-southeast-1";
    case 7 : 
        return "ap-southeast-2";
    case 8 : 
        return "ca-central-1";
    case 9 : 
        return "eu-central-1";
    case 10 : 
        return "eu-west-1";
    case 11 : 
        return "eu-west-2";
    
  }
}

exports.makeOperationString = makeOperationString;
exports.makeRegionString = makeRegionString;
/* No side effect */
