// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function makeOperationString(param) {
  switch (param) {
    case /* SignUp */0 :
        return "SignUp";
    case /* SignIn */1 :
        return "SignIn";
    case /* SignOut */2 :
        return "SignOut";
    case /* ConfirmSignUp */3 :
        return "ConfirmSignUp";
    case /* ChangePassword */4 :
        return "ChangePassword";
    case /* RespondToAuthChallenge */5 :
        return "RespondToAuthChallenge";
    case /* ForgotPassword */6 :
        return "ForgotPassword";
    case /* ConfirmForgotPassword */7 :
        return "ConfirmForgotPassword";
    case /* InitiateAuth */8 :
        return "InitiateAuth";
    
  }
}

function makeRegionString(param) {
  switch (param) {
    case /* UsEast1 */0 :
        return "us-east-1";
    case /* UsEast2 */1 :
        return "us-east-2";
    case /* UsWest2 */2 :
        return "us-west-2";
    case /* ApSouth1 */3 :
        return "ap-south-1";
    case /* ApNortheast1 */4 :
    case /* ApNortheast2 */5 :
        return "ap-northeast-2";
    case /* ApSoutheast1 */6 :
        return "ap-southeast-1";
    case /* ApSoutheast2 */7 :
        return "ap-southeast-2";
    case /* CaCentral1 */8 :
        return "ca-central-1";
    case /* EuCentral1 */9 :
        return "eu-central-1";
    case /* EuWest1 */10 :
        return "eu-west-1";
    case /* EuWest2 */11 :
        return "eu-west-2";
    
  }
}

function makeAwsGenericErrors(param) {
  var message = param[/* message */1];
  switch (param[/* __type */0]) {
    case "InternalErrorException" :
        return /* `CognitoInternalError */[
                636052602,
                message
              ];
    case "InvalidLambdaResponseException" :
        return /* `CognitoInvalidLambdaResponse */[
                -1072578002,
                message
              ];
    case "InvalidParameterException" :
        return /* `CognitoInvalidParameter */[
                -267133469,
                message
              ];
    case "NotAuthorizedException" :
        return /* `CognitoNotAuthorized */[
                -1019683139,
                message
              ];
    case "ResourceNotFoundException" :
        return /* `CognitoResourceNotFound */[
                281060686,
                message
              ];
    case "TooManyRequestsException" :
        return /* `CognitoTooManyRequests */[
                165203366,
                message
              ];
    case "UnexpectedLambdaException" :
        return /* `CognitoUnexpectedLambda */[
                -539579927,
                message
              ];
    case "UserLambdaValidationException" :
        return /* `CognitoUserLambdaValidation */[
                1019055420,
                message
              ];
    default:
      return ;
  }
}

function makeConfirmSignUpErrors(err) {
  var match = makeAwsGenericErrors(err);
  if (match !== undefined) {
    return match;
  } else {
    var message = err[/* message */1];
    switch (err[/* __type */0]) {
      case "CodeDeliveryFailureException" :
          return /* `CognitoCodeDeliveryFailure */[
                  307717752,
                  message
                ];
      case "InvalidEmailRoleAccessPolicyException" :
          return /* `CognitoInvalidEmailRoleAccessPolicy */[
                  -320011326,
                  message
                ];
      case "InvalidPasswordException" :
          return /* `CognitoInvalidPassword */[
                  -17702879,
                  message
                ];
      case "InvalidSmsRoleAccessPolicysException" :
          return /* `CognitoInvalidSmsRoleAccessPolicys */[
                  598714580,
                  message
                ];
      case "InvalidSmsRoleTrustRelationshipException" :
          return /* `CognitoInvalidSmsRoleTrustRelationship */[
                  -198400121,
                  message
                ];
      case "UsernameExistsException" :
          return /* `CognitoUsernameExists */[
                  -157849469,
                  message
                ];
      default:
        return /* ReasonCognitoUnknownError */536808491;
    }
  }
}

function makeSignUpErrors(err) {
  var match = makeAwsGenericErrors(err);
  if (match !== undefined) {
    return match;
  } else {
    var message = err[/* message */1];
    switch (err[/* __type */0]) {
      case "CodeDeliveryFailureException" :
          return /* `CognitoCodeDeliveryFailure */[
                  307717752,
                  message
                ];
      case "InvalidEmailRoleAccessPolicyException" :
          return /* `CognitoInvalidEmailRoleAccessPolicy */[
                  -320011326,
                  message
                ];
      case "InvalidPasswordException" :
          return /* `CognitoInvalidPassword */[
                  -17702879,
                  message
                ];
      case "InvalidSmsRoleAccessPolicysException" :
          return /* `CognitoInvalidSmsRoleAccessPolicys */[
                  598714580,
                  message
                ];
      case "InvalidSmsRoleTrustRelationshipException" :
          return /* `CognitoInvalidSmsRoleTrustRelationship */[
                  -198400121,
                  message
                ];
      case "UsernameExistsException" :
          return /* `CognitoUsernameExists */[
                  -157849469,
                  message
                ];
      default:
        return /* ReasonCognitoUnknownError */536808491;
    }
  }
}

exports.makeOperationString = makeOperationString;
exports.makeRegionString = makeRegionString;
exports.makeAwsGenericErrors = makeAwsGenericErrors;
exports.makeConfirmSignUpErrors = makeConfirmSignUpErrors;
exports.makeSignUpErrors = makeSignUpErrors;
/* No side effect */
