// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -866061109,
    "ChangePassword"
  ],
  /* tuple */[
    -606583560,
    "ConfirmSignUp"
  ],
  /* tuple */[
    -384135774,
    "SignIn"
  ],
  /* tuple */[
    -384133096,
    "SignUp"
  ],
  /* tuple */[
    -263444194,
    "ConfirmForgotPassword"
  ],
  /* tuple */[
    -23567743,
    "InitiateAuth"
  ],
  /* tuple */[
    551525291,
    "RespondToAuthChallenge"
  ],
  /* tuple */[
    851876926,
    "ForgotPassword"
  ]
];

function operationToJs(param) {
  return Js_mapperRt.binarySearch(8, param, jsMapperConstantArray);
}

function operationFromJs(param) {
  return Js_mapperRt.revSearch(8, jsMapperConstantArray, param);
}

var jsMapperConstantArray$1 = /* array */[
  /* tuple */[
    -848419190,
    "USER_SRP_AUTH"
  ],
  /* tuple */[
    -65181422,
    "REFRESH_TOKEN_AUTH"
  ],
  /* tuple */[
    191049237,
    "REFRESH_TOKEN"
  ],
  /* tuple */[
    204375576,
    "USER_PASSWORD_AUTH"
  ],
  /* tuple */[
    204375576,
    "USER_PASSWORD_AUTH"
  ],
  /* tuple */[
    950373878,
    "CUSTOM_AUTH"
  ],
  /* tuple */[
    1021659844,
    "ADMIN_NO_SRP_AUTH"
  ]
];

function authenticationFlowTypeToJs(param) {
  return Js_mapperRt.binarySearch(7, param, jsMapperConstantArray$1);
}

function authenticationFlowTypeFromJs(param) {
  return Js_mapperRt.revSearch(7, jsMapperConstantArray$1, param);
}

exports.operationToJs = operationToJs;
exports.operationFromJs = operationFromJs;
exports.authenticationFlowTypeToJs = authenticationFlowTypeToJs;
exports.authenticationFlowTypeFromJs = authenticationFlowTypeFromJs;
/* No side effect */
